include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

# CUDA.jl

cuda:1.5:
  image: ubuntu:bionic
  extends:
    - .julia:1.5
    - .test
  tags:
    - nvidia


# AMDGPU.jl

amdgpu:1.5:
  image: rocm/dev-ubuntu-18.04
  extends:
    - .julia:1.5
    - .test
  tags:
    - rocm
  allow_failure: true


# other tasks

coverage:
  extends:
    - .julia:1.5
    - .coverage
